version: "3.8"

services:

  sonar:
    image: sonarqube:community
    container_name: sonarqube
    depends_on:
      - postgres
    ports:
      - "9000:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    networks:
      - guisauto_network

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    networks:
      - guisauto_network

  mongo:
    image: mongo:6
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: davguisadonunez
      MONGO_INITDB_ROOT_PASSWORD: davguisadonunez
    volumes:
      - mongo_data:/data/db
    networks:
      - guisauto_network

  backend:
    build: .
    container_name: backend_api
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - mailhog
    networks:
      - guisauto_network
    environment:
      NODE_ENV: production
      MONGO_URI: "mongodb+srv://davguisadonunez:davguisadonunez@concesionariodb.ux7pn.mongodb.net/?retryWrites=true&w=majority"
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
      MAIL_FROM: "no-reply@guisauto.com"
    command: ["npm", "run", "start"]

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    restart: always
    ports:
      - "1025:1025" # Puerto SMTP
      - "8025:8025" # Interfaz web
    networks:
      - guisauto_network

volumes:
  mongo_data:

networks:
  guisauto_network:
    driver: bridge
